### ISSUE TITLE
performance reduced in 6.x

### ISSUE THREAD

**Issue by tyan-boot** [xacrimon/dashmap#306]
After upgrade to version 6.0.1, it seems the latency increased, here is my benchmark result using criterion:

```
Maps/dash-map/read/v5   time:   [165.64 ns 171.17 ns 176.44 ns]
                        change: [-4.5163% +1.9547% +8.3860%] (p = 0.55 > 0.05)
                        No change in performance detected.
Maps/dash-map/read/v6   time:   [342.38 ns 354.98 ns 366.45 ns]
                        change: [-7.5138% +2.9050% +15.397%] (p = 0.61 > 0.05)
                        No change in performance detected.
```

This my code used to benchmark:

```rust
use criterion::{BatchSize, Criterion, criterion_group, criterion_main};
use dashmap::DashMap;
use dashmap6::{DashMap as DashMap6};

type MyID = [u8; 5];

fn bench_maps(c: &mut Criterion) {
    let mut group = c.benchmark_group("Maps");
    group.bench_function("dash-map/read/v5", |b| {
        b.iter_batched(
            || {
                let maps = DashMap::new();
                maps.insert(MyID::from([1, 2, 3, 4, 5]), MyID::default());
                maps
            },
            |maps| {
                criterion::black_box(maps.get(&MyID::from([1, 2, 3, 4, 5])));
            },
            BatchSize::SmallInput,
        )
    });
    group.bench_function("dash-map/read/v6", |b| {
        b.iter_batched(
            || {
                let maps = DashMap6::new();
                maps.insert(MyID::from([1, 2, 3, 4, 5]), MyID::default());
                maps
            },
            |maps| {
                criterion::black_box(maps.get(&MyID::from([1, 2, 3, 4, 5])));
            },
            BatchSize::SmallInput,
        )
    });
}

criterion_group!(benches, bench_maps);
criterion_main!(benches);
``` 

`Cargo.toml`
```toml
[dependencies]
dashmap = { version = "5.5.3", features = ["inline"] }
dashmap6 = { version = "6", package = "dashmap", features = ["inline"] }


[dev-dependencies]
criterion = "0.5.1"

[[bench]]
name = "map"
path = "benches/map.rs"
harness = false
```

### Environment
Tested on Apple M1, M2, both running macOS
Also test on AMD 5600G which runs Windows 11

Rust version output by `rustc -vV`

```
rustc 1.79.0 (129f3b996 2024-06-10)
binary: rustc
commit-hash: 129f3b9964af4d4a709d1383930ade12dfe7c081
commit-date: 2024-06-10
host: aarch64-apple-darwin
release: 1.79.0
LLVM version: 18.1.7
```
